import {
  anex,
  autochair,
  bathCat,
  bebivita,
  bedCat,
  car,
  carriage,
  carriageCat,
  chair,
  clothes,
  discount,
  feeding,
  goods,
  hipp,
  huggies,
  lego,
  newThings,
  pampers,
  playdoh,
  potCat,
  puzzlesCat,
  room,
  roomCat,
  soap,
  toy,
} from '../assets';

export const catalogList = [
  {
    id: '1',
    name: 'Дитячі коляски',
    link: '#',
    logo: carriage,
    subList: [
      { id: 'carriages', name: 'Коляски 2 в 1', link: '#' },
      { id: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '2',
    name: 'Дитяча кімната',
    link: '#',
    logo: room,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test2', name: 'test2', link: '#' },
    ],
  },
  {
    id: '3',
    name: 'Стільці і шезлонги',
    link: '#',
    logo: chair,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test2', name: 'test2', link: '#' },
    ],
  },
  {
    id: '4',
    name: 'Для годування',
    link: '#',
    logo: feeding,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test2', name: 'test2', link: '#' },
    ],
  },
  {
    id: '5',
    name: 'Гігієна і догляд',
    link: '#',
    logo: soap,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test2', name: 'test2', link: '#' },
    ],
  },
  {
    id: '6',
    name: 'Автокрісла',
    link: '#',
    logo: autochair,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test2', name: 'test2', link: '#' },
    ],
  },
  {
    id: '7',
    name: 'Дитячий транспорт',
    link: '#',
    logo: car,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test2', name: 'test2', link: '#' },
    ],
  },
  {
    id: '8',
    name: 'Іграшки',
    link: '#',
    logo: toy,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test2', name: 'test2', link: '#' },
    ],
  },
  {
    id: '9',
    name: 'Одяг',
    link: '#',
    logo: clothes,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test2', name: 'test2', link: '#' },
    ],
  },
  {
    id: '10',
    name: 'Новий товар',
    link: '#',
    logo: newThings,
    subList: [
      { id: 'test1', name: 'test1', link: '#' },
      { id: 'test3', name: 'test3', link: '#' },
    ],
  },
];
export const discountSliderData = [
  {
    id: '1',
    name: 'First',
    image: discount,
  },
  {
    id: '2',
    name: 'Second',
    image: discount,
  },
  {
    id: '3',
    name: 'Third',
    image: discount,
  },
  {
    id: '4',
    name: 'Fourth',
    image: discount,
  },
];
export const promotionalProducts = [
  {
    id: '1',
    image: goods,
    name: 'test',
    description: 'first',
    prevPrice: 6000,
    currPrice: 5000,
  },
  {
    id: '2',
    image: goods,
    name: 'test',
    description: 'second',
    prevPrice: 4000,
    currPrice: 3500,
  },
  {
    id: '3',
    image: goods,
    name: 'test',
    description: 'second',
    prevPrice: 4000,
    currPrice: 3500,
  },
  {
    id: '4',
    image: goods,
    name: 'test',
    description: 'second',
    prevPrice: 4000,
    currPrice: 3500,
  },
  {
    id: '5',
    image: goods,
    name: 'test',
    description: 'second',
    prevPrice: 4000,
    currPrice: 3500,
  },
  {
    id: '6',
    image: goods,
    name: 'test',
    description: 'second',
    prevPrice: 4000,
    currPrice: 3500,
  },
];
export const popularCategory = [
  { id: '1', image: carriageCat, name: 'Коляски 2в1' },
  { id: '2', image: bathCat, name: 'Ліжечка' },
  { id: '3', image: bedCat, name: 'Горщики' },
  { id: '4', image: potCat, name: 'Постільна білизна' },
  { id: '5', image: roomCat, name: 'Пазли' },
  { id: '6', image: puzzlesCat, name: 'Ванночки' },
];

export const brands = [
  { id: '1', name: 'Play Doh', image: playdoh },
  { id: '2', name: 'Huggies', image: huggies },
  { id: '3', name: 'Hipp', image: hipp },
  { id: '4', name: 'Pampers', image: pampers },
  { id: '5', name: 'Anex', image: anex },
  { id: '6', name: 'Lego', image: lego },
  { id: '7', name: 'Bebivita', image: bebivita },
  { id: '8', name: 'Bebivita', image: bebivita },
  { id: '9', name: 'Anex', image: anex },
  { id: '10', name: 'Lego', image: lego },
  { id: '11', name: 'Bebivita', image: bebivita },
  { id: '12', name: 'Bebivita', image: bebivita },
];
