import {
  anex,
  autoChair,
  bathCat,
  bebivita,
  bedCat,
  car,
  carriage,
  carriageCat,
  chair,
  clothes,
  discount,
  feeding,
  hipp,
  huggies,
  lego,
  newThings,
  pampers,
  playdoh,
  potCat,
  puzzlesCat,
  room,
  roomCat,
  soap,
  toy,
} from '../assets';

export const catalogList = [
  {
    id: '1',
    name: 'Дитячі коляски',
    code: 'carriage',
    link: '#',
    logo: carriage,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '2',
    name: 'Дитяча кімната',
    code: 'room',
    link: '#',
    logo: room,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '3',
    name: 'Стільці і шезлонги',
    code: 'chair',
    link: '#',
    logo: chair,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '4',
    name: 'Для годування',
    code: 'feeding',
    link: '#',
    logo: feeding,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '5',
    name: 'Гігієна і догляд',
    code: 'soap',
    link: '#',
    logo: soap,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '6',
    name: 'Автокрісла',
    code: 'autoChair',
    link: '#',
    logo: autoChair,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '7',
    name: 'Дитячий транспорт',
    code: 'car',
    link: '#',
    logo: car,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '8',
    name: 'Іграшки',
    code: 'toy',
    link: '#',
    logo: toy,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '9',
    name: 'clothes',
    code: 'toy',
    link: '#',
    logo: clothes,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
  {
    id: '10',
    name: 'Новий товар',
    code: 'newThings',
    link: '#',
    logo: newThings,
    categories: [
      { id: '1', code: 'carriage', name: 'Коляски 2 в 1', link: '#' },
      { id: '2', code: 'envelopes', name: 'Зимові конверти', link: '#' },
      { id: '3', code: 'components', name: 'Аксесуари та комплектуючі', link: '#' },
      { id: '4', code: 'couplings', name: 'Муфти', link: '#' },
    ],
  },
];
export const discountList = [
  {
    id: '1',
    name: 'First',
    image: discount,
  },
  {
    id: '2',
    name: 'Second',
    image: discount,
  },
  {
    id: '3',
    name: 'Third',
    image: discount,
  },
  {
    id: '4',
    name: 'Fourth',
    image: discount,
  },
];
export const producersList = [
  { id: '1', name: 'Anex', code: 'anex' },
  { id: '2', name: 'Bair', code: 'bair' },
  { id: '3', name: 'BabyOno', code: 'babyono' },
  { id: '4', name: 'Corrello', code: 'corrello' },
  { id: '5', name: 'OK Baby', code: 'okbaby' },
  { id: '6', name: 'Babyroom', code: 'babyroom' },
  { id: '7', name: 'ZD', code: 'zd' },
  { id: '8', name: 'Маленька Соня', code: 'littlesonia' },
  { id: '9', name: 'Espiro', code: 'espiro' },
];
export const productsList = [
  {
    id: '1',
    isAvailable: true,
    fullName: 'Коляска 2в1 Anex M/Type Dune mt-01Q',
    name: 'Коляска',
    code: 'EP-01',
    colors: ['blue', 'red', 'green'],
    sex: ['male', 'female'],
    catalog: 'carriage',
    category: 'carriage',
    producer: 'Anex',
    price: 5000,
    discount: {
      isDiscount: true,
      price: 4000,
    },
    photos: {
      blue: [anex, discount],
      red: [],
      green: [],
    },
  },
  {
    id: '2',
    isAvailable: true,
    fullName: 'Іграшка-головоломка Same Toy IQ Ball Cube',
    name: 'Іграшка-головоломка',
    code: 'EP-01',
    // colors: ['blue', 'red', 'green'],
    // sex: ['male', 'female'],
    catalog: 'toy',
    category: 'carriage',
    producer: 'BabyOno',
    price: 200,
    discount: {
      isDiscount: true,
      price: 150,
    },
    images: [anex, discount],
  },
  {
    id: '3',
    isAvailable: true,
    fullName: 'Пляшечка 130 мл',
    name: 'Пляшечка',
    code: 'EP-01',
    colors: ['blue', 'red', 'green'],
    sex: ['male', 'female'],
    catalog: 'carriage',
    category: 'envelopes',
    producer: 'BabyOno',
    price: 100,
    discount: {
      isDiscount: false,
    },
    photos: {
      blue: [anex, discount],
      red: [],
      green: [],
    },
  },
];
export const popularCategory = [
  { id: '1', image: carriageCat, name: 'Коляски 2в1' },
  { id: '2', image: bathCat, name: 'Ліжечка' },
  { id: '3', image: bedCat, name: 'Горщики' },
  { id: '4', image: potCat, name: 'Постільна білизна' },
  { id: '5', image: roomCat, name: 'Пазли' },
  { id: '6', image: puzzlesCat, name: 'Ванночки' },
];
export const brandsList = [
  { id: '1', name: 'Play Doh', image: playdoh },
  { id: '2', name: 'Huggies', image: huggies },
  { id: '3', name: 'Hipp', image: hipp },
  { id: '4', name: 'Pampers', image: pampers },
  { id: '5', name: 'Anex', image: anex },
  { id: '6', name: 'Lego', image: lego },
  { id: '7', name: 'Bebivita', image: bebivita },
  { id: '8', name: 'Bebivita', image: bebivita },
  { id: '9', name: 'Anex', image: anex },
  { id: '10', name: 'Lego', image: lego },
  { id: '11', name: 'Bebivita', image: bebivita },
  { id: '12', name: 'Bebivita', image: bebivita },
];
